( Galactifun ) Upstream update
SlimeTraditionalTranslation/Galactifun pull request #38
Opened 2022-08-10 10:07 UTC by xwinhyukx

DEV - 65 & 66

2022-08-11 03:42 UTC, xMikux requested changes
需要合併最新的上游

2022-08-11 13:02 UTC, xwinhyukx commented
上游發布了最新更新

DEV- 67 & 68

2022-08-12 06:14 UTC, xMikux requested changes
仍然需要再更新一次上游

2022-08-12 11:19 UTC, xwinhyukx commented
DEV- 69

Upstream 發布了最新更新
未經過測試.

2022-08-14 03:59 UTC, xMikux requested changes

2022-08-14 03:59 UTC, xMikux commented on src/main/java/io/github/addoncommunity/galactifun/base/BaseItems.java
> +            "&7阻止空氣通過, 但充許實體"
允許不是充許

2022-08-14 03:59 UTC, xMikux commented on src/main/java/io/github/addoncommunity/galactifun/base/items/protection/ForcefieldGenerator.java
> +                p.sendMessage("取消激活");
已停用

2022-08-14 03:59 UTC, xMikux commented on src/main/java/io/github/addoncommunity/galactifun/base/items/protection/ForcefieldGenerator.java
> +                p.sendMessage("已激活");
已啟用

2022-08-14 03:59 UTC, xMikux commented on src/main/java/io/github/addoncommunity/galactifun/util/Util.java
> +            return "%.3f ly".formatted(distance);
缺失翻譯

2022-08-14 03:59 UTC, xMikux commented on src/main/java/io/github/addoncommunity/galactifun/util/Util.java
> +            return "%.3f km".formatted(distance * KM_PER_LY);
缺失翻譯

2022-08-14 11:04 UTC, xwinhyukx commented
Text error correction

2022-08-14 14:41 UTC, xMikux approved these changes

2022-08-14 14:41 UTC, merged